### ISSUE TITLE
Addons can't be opened while Gmod is running

### ISSUE THREAD

**Issue by JohnnyCrazy** [whisperity/SharpGMad#8]
For Testers/Developers it would be cool, to open addons which are currently loaded into gmod

ATM, it throws a "Can't-acess-Error", because an other application is using the file. A solution would be, to open the file with ReadOnly attributes, and tell the user, that he can't make changes to it.(Just extract/preview the files)

Will look into this soon

**Comment by whisperity** [comment]
I'm guessing the exception is thrown also if the file is locked by any other application.
You should first check if gmod allows read sharing.

But of course, it'll be only a few lines of code to be changed.
Should the user be warned that the file is opened read-only and should we **disallow** saving entirely or just make the user "Save as...".

Just to tell you (if you didn't read the full code) SharpGMad, due to how gmas work, does not rewrite the opened file while saving, but create a whole new file and copy it over thereafter. [The corresponding code](https://github.com/whisperity/SharpGMad/blob/master/SharpGMad/RealtimeAddon.cs#L585)

For a moment I thought it is not neccessary to eveb have Write rights on the `AddonStream`, but after looking at the code I realised I am using `Stream.CopyTo` and not `File.Copy`.

**Comment by whisperity** [comment]
(Side note: if you're going to make a pull request, please use a topic branch instead of your `master` and pull in my changes, so your previous, not yet marked as _merged_ pull request does not get added with commits.
(It will be marked (I hope…) as merged after I push a new revision to master. You could use my develop as the base branch of your request.)

**Comment by JohnnyCrazy** [comment]
Okay,

I will look through it and see, what needs to be done and what would be the best method.

Thanks for the side note :smiley: 
btw, is it okay, to make the changes in my forked "develop" branch? Sorry for asking, thats the first time i really work with GitHub (forking/pull request etc.)

**Comment by whisperity** [comment]
While they are technically possible, because the way pull requests work on GitHub, discouraged. Pulls are instantly updated and added a commit when you push to the branch marked as the request's head. This ensures that when we discuss a PRq and you decide to add something else, you don't have to create a new one.

But this raises a problem. Upstream branches (the copy of my `master` and `develop` in your repository) should stay what they are for: tracking and making upstream changes available to you. They should **never** be used as request heads (source branch). On long running pull requests, this makes tracking your changes incredibly hard.

You should create a new branch. The name can be arbitary, but in general, descriptive (for example: `readonly-loading` in this case) and you should commit to that branch and push it to your fork and then make the request from that. This leaves upstream out of the question until merged.

Another good thing with _topic branches_ (the above paragraph simply explains what they are used for: to contain commits for one certain topic) is that if upstream (my code: master or develop) changes while you are working on your addition, you can easily `rebase` your commits to be on top of my changes, so there won't be unneccessary merges in the history. This is also the generally recommended workflow for OSS projects. I could explain more but at work at the moment, but I can recommend you heading to [git-scm.com](http://git-scm.com) and read the _Pro Git_ book. It really explains stuff nice.

**Comment by JohnnyCrazy** [comment]
Alright, thanks for the explaination and the link.

I read through it (it's indeed very well written) and got how merging with forks works.

I will try to find out what gmod is doing with loaded gmas.

**Comment by whisperity** [comment]
Thanks for your contribution. :smile: I'll avoid fixing this issue and wait for your changes, if you wish.

**Comment by JohnnyCrazy** [comment]
Soooo,

There are basically 2 main things, which should be discussed.

1.
The problem is, you can't continiously check, if the file is locked. That means, you could open the FileStream while the gma is totaly unlocked and "free". But then gmod starts and locks the file. I don't really know how FileStreams react on such situations. To fix it, you(we) would need to rewrite the FileStream usage:

<pre>using(FileStream fs = new FileStream(bla)) { }</pre>

Since that would check every call, wether the file is locked or not (It would be a lot of work to rewrite it...)

2.
In my opinion(and in the upcoming pull-request), i decided to implement a "Read-Only" mode, which disables every Button/Function, which would write sth into the FileStream.(Update Metadata/Update file/Add File)(What are your thoughts, should the buttons be disabled or completly invisible?)
Before the file gets opened in Read-Only mode, the user is asked, if he wants to make a copy of the file and open this one.

Gonna make the Pull-Request tomorrow, need to tidy up some stuff :grin:

**Comment by whisperity** [comment]
0) Thanks :grinning:

---

1) No, I don't think rewriting the way we handle files is a good idea. A continuously open stream is better as it keeps the file locked and less error prone. I didn't test it, but I **guess** that if a FileStream write generates an `IOException` when it was opened without a lock and got locked thereafter.
There are two ways in my point of view:
- :lock_with_ink_pen: The first is that when SharpGMad opens the file, we assume full lock on it. Hence this is an _editor_ program, it's perfectly understandable that we think we have rights to write the file. And with this, gmod is out of play until the file is released.
- :lock: The other is still a locking one, but we allow other applications (aka gmod) to read the file.

Write rights should be reserved at all costs. How gmod handles this is not exactly our question right now, and by definition, gma files are continuous streams not really showing the intent to be edited internally.

I have already [linked you this code](https://github.com/whisperity/SharpGMad/blob/b62e8bafac0a73eafca727e1cafe635b903724f9/SharpGMad/RealtimeAddon.cs#L585) about the "workaround" how we save the files. A third option would be that if an `IOException` is caught when we try to save, we prompt the user to _Save as..._ somewhere else. (But then again, we need to differentiate between "this file is open in gmod" kind of `IOException`s and other ones...) I don't think this would also be the solution to this problem. Simply, if a file is in editing mode, it is in editing mode. The question is: **Should we give read share?**

---

2) Having the controls disabled is visually more powerful than totally hiding them. If it **is** there but grayed out, the user will be thinking "Why can't I do this if the option is there?" instead of "This program does not have this functionality". So it is visually re-enacted every time that the addon is open read-only.

**Comment by JohnnyCrazy** [comment]
0) No Problem :smiley: 

1) Okay, putting it all together, this would be a good solution:
- Always try to open the FileStream with Write permissions
- If we can't, open it with write permissions, open it with readOnly permissions
- If the User wanna save AND we only have Read-permissions, open a File-Save Dialog to a new File

2) Well, if we use the solution above, we don't really need to grey out buttons at all, do we?

Tell me what you think,

**Comment by whisperity** [comment]
I think the "Save as..." method creates unnecessary hassle for the user as he has to rename/overwrite the file if he wishes the new content to be loaded.

I think a better solution would be:
- Try to open the file `ReadWrite` (with optional `Read` share? _I am not sure whether sharing the Read rights is good either._) like it happens now
- If can't, prompt the user that the file should be opened read-only, and block all destructive access.
- (If the user chooses not to open the file read-only, noop.)

We give them the possibility to examine locked files, but reserve the view that they are using an editor they **can't** use, because the file is locked. And if they want to modify a file, they should make sure that the file **is** modifiable (i.e.: close gmod and let the lock dispose).

**Comment by whisperity** [comment]
Oh and also, I summon forth @garrynewman and request that he gives us some insight how GMAs are handled within his Mod. :smile:

**Comment by JohnnyCrazy** [comment]
Alright, final solution achieved :smile: 
Already did some stuff in my [branch](https://github.com/JohnnyCrazy/SharpGMad/tree/issue8).
I will adapt it to our final solution tomorrow, since i did too much at all. :smile: 

Okay, let's see what garry can tell us :+1:

**Comment by whisperity** [comment]
> Just to say it for the record... :red_circle:
> As of right now, Garry's Mod opens the GMA files for reading and with subsequent read shares enabled.

**Comment by JohnnyCrazy** [comment]
Alright, well, then this is propably the best solution we can implement ATM.

Would be nice if he could implement an Reload-Thing like on windows gamemodes (They get auto-reloaded on File-Change)

**Comment by whisperity** [comment]
Indeed, but reloading a single Lua code (which is an interpreted scripting file) is (I think) much easier than reloading a sequential archive. GMA files are still sequential the most sequentiality can get (_cough_ that big damn CRC at the end :grinning:) and I am not exactly sure whether Source itself support on-the-fly reloading of textures and models.
(But a lot of stuff can be hacked. Gmod did this already.)
